version: '3.8'

services:
  backend:
    build: ./backend
    container_name: guildcon_backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
      - backend_uploads:/app/static/uploads
    environment:
      - SECRET_KEY=${SECRET_KEY:-supersecretkey}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-guildcon2025}
    restart: unless-stopped
    networks: [guildcon]

  web:
    image: node:20
    container_name: guildcon_web
    restart: unless-stopped
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run start -- -p 8080 -H 0.0.0.0"
    environment:
      NODE_ENV: production
      PORT: 8080
      API_URL: http://backend:8000
      NEXT_PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./:/app
    depends_on:
      - backend
    ports:
      - "${WEB_PORT:-8080}:8080"
    networks: [guildcon]

networks:
  guildcon: {}

volumes:
  backend_data: {}
  backend_uploads: {}