version: '3.9'

services:
  db:
    image: postgres:16
    container_name: guildcon_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PGUSER:-directus}
      POSTGRES_PASSWORD: ${PGPASSWORD:-directus}
      POSTGRES_DB: ${PGDATABASE:-guildcon}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [guildcon]

  directus:
    image: directus/directus:latest
    container_name: guildcon_directus
    restart: unless-stopped
    depends_on: [db]
    environment:
      KEY: ${DIRECTUS_KEY:-changeme}
      SECRET: ${DIRECTUS_SECRET:-changeme}
      ADMIN_EMAIL: ${DIRECTUS_ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${DIRECTUS_ADMIN_PASSWORD:-ChangeMe123!}
      DB_CLIENT: 'pg'
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${PGDATABASE:-guildcon}
      DB_USER: ${PGUSER:-directus}
      DB_PASSWORD: ${PGPASSWORD:-directus}
      PUBLIC_URL: ${DIRECTUS_PUBLIC_URL:-http://localhost:${DIRECTUS_PORT:-8055}}
      CORS_ENABLED: 'true'
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
    ports:
      - "${DIRECTUS_PORT:-8055}:8055"
    volumes:
      - directus_uploads:/directus/uploads
      - ./directus:/directus/extensions:ro
    networks: [guildcon]

  web:
    image: node:20
    container_name: guildcon_web
    restart: unless-stopped
    working_dir: /app
    command: sh -lc "npm ci && npm run build && npm run start -p ${WEB_PORT:-8080}"
    environment:
      NODE_ENV: production
      PORT: ${WEB_PORT:-8080}
      DIRECTUS_URL: ${DIRECTUS_URL:-http://directus:8055}
      DIRECTUS_TOKEN: ${DIRECTUS_TOKEN:-changeme-service-token}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-change-me-long-random}
    volumes:
      - ./:/app
    depends_on: [directus]
    ports:
      - "${WEB_PORT:-8080}:${WEB_PORT:-8080}"
    networks: [guildcon]

networks:
  guildcon: {}

volumes:
  pgdata: {}
  directus_uploads: {}

